version: 2
updates:
  - package-ecosystem: "maven"  # Use "npm", "pip", etc., for other ecosystems
    directory: "/"  # Path to your dependency file (e.g., pom.xml)
    schedule:
      interval: "weekly"  # Options: daily, weekly, monthly
    open-pull-requests-limit: 5
